### ISSUE TITLE
Staff and other bots being punished

### ISSUE THREAD

**Issue by Gilbat** [Cubic-Chunks-Development-Team/llama-bot#6]
Simple enough, we should add a way to let users select certain roles to not be noticed by llamabot's spam system.

**Comment by james5922** [comment]
Closed in f8c5c44.

**Comment by james5922** [comment]
Partially closed in #7.

Added some bots that I often use, but no coding for this was done either.

**Comment by james5922** [comment]
Partially closed in 0420cf7 and #8.

Bot support now active, but by-role selection is not implemented.

**Comment by james5922** [comment]
See pull request #11.

**Comment by james5922** [comment]
Closed in #11.
